# API keys file

### Ethos Tekne
CONSUMER_KEY: 'this needs to be replaced'
CONSUMER_SECRET: 'this needs to be replaced'
ACCESS_TOKEN: 'this needs to be replaced'
ACCESS_TOKEN_SECRET: 'this needs to be replaced'